#DB
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MUK_TABLE
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
    hikari:
      # PoolSize = Tn x (Cm - 1) + (Tn / 2)
      # Tn: 전체 Thread 갯수
      # Cm: 하나의 Task에서 동시에 필요한 Connection 수
      maximum-pool-size: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      poolName: HikariCP
      readOnly: false
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      # create: 애플리케이션 실행 시 테이블을 모두 제거하고 다시 생성합니다. (drop & create)
      # create-drop: 애플리케이션 실행 시 테이블을 모두 제거하고 다시 생성합니다. 그리고 애플리케이션 종료 시점에 테이블을 모두 제거합니다. (drop & create & drop)
      # update: 애플리케이션 실행 시 변경점만 반영됩니다.
      # validate: 현재 테이블 정보가 entity에 정의된 내용과 동일한지 체크합니다. 다를 경우 경고를 출력하며 애플리케이션을 실행시키지 않습니다.
      # none: 자동생성을 사용하지 않습니다.
    properties:
      hibernate:
        query:
          in_clause_parameter_padding: true
        show_sql: false  # sql 쿼리를 보여줍니다.
        format_sql: true  # sql query formatting
    generate-ddl: false
    defer-datasource-initialization: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

#swagger
springdoc:
  # spring boot 웹 애플리케이션의 api를 OpenAPI 3을 이용하여 json 형식화 한것의 경로
  api-docs:
    path: /docs
  # request media type 의 기본 값
  default-consumes-media-type: application/json
  # response media type 의 기본 값
  default-produces-media-type: application/json
  swagger-ui:
    # 태그 내 각 api의 정렬 기준
    operations-sorter: alpha
    # 태그 정렬 기준
    tags-sorter: alpha
    # Swagger HTML 문서 경로
    path: /web/swagger-ui
    # swagger-ui default url인 petstore html 문서 비활성화 여부
    disable-swagger-default-url: true
    # json화 된 config파일 대신 파라미터를 이용하여 swagger-ui에 접근하도록 합니다
    display-query-params-without-oauth2: true
    # tag와 operation을 펼치는 방식에 대한 설정
    doc-expansion: list
  # OpenAPI 3 로 문서화할 api path 리스트
  paths-to-match: /**
  cache:
    disabled: true